# 聚合操作


In [1]:
import numpy as np

L = np.random.random(100)

In [2]:
L

array([0.14008015, 0.15078988, 0.83223598, 0.65146419, 0.99265105,
       0.36452182, 0.08151545, 0.3731073 , 0.90048423, 0.79317737,
       0.24179751, 0.01947762, 0.05151602, 0.66422996, 0.25888066,
       0.89989241, 0.77376226, 0.03053919, 0.17571328, 0.92045125,
       0.65965939, 0.03063386, 0.29682146, 0.45289668, 0.75254022,
       0.71366851, 0.9944442 , 0.16115071, 0.90813839, 0.47900313,
       0.86718387, 0.70613412, 0.32562176, 0.36449376, 0.38095454,
       0.42445064, 0.16345126, 0.15487858, 0.45938086, 0.9091577 ,
       0.48904375, 0.10964708, 0.38841831, 0.81603216, 0.11630387,
       0.85184076, 0.43422529, 0.35122589, 0.89864692, 0.12228016,
       0.70619959, 0.47543257, 0.74703021, 0.0657917 , 0.78744732,
       0.03261999, 0.38824602, 0.72758666, 0.96391216, 0.38749186,
       0.30840764, 0.51987241, 0.94262139, 0.47882592, 0.54424215,
       0.16074785, 0.94553487, 0.61453931, 0.63228553, 0.85336241,
       0.49563423, 0.41541963, 0.15730026, 0.10081464, 0.51868

In [3]:
sum(L) # 计算L数组的和

51.875780833654645

In [4]:
np.sum(L) # 计算L数组的和

51.875780833654645

In [5]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array) # 效率很高

147 ms ± 3.86 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
388 µs ± 3.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
np.min(big_array) # 求最小值

1.592697569385848e-07

In [7]:
np.max(big_array) # 求最大值

0.9999999608614992

In [8]:
big_array.min() # 最小值

1.592697569385848e-07

In [9]:
big_array.max() # 最大值

0.9999999608614992

In [10]:
big_array.sum() # 求和

500285.8723133392

In [11]:
X = np.arange(16).reshape((4, -1))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X) # 矩阵所有元素之和

120

In [13]:
np.sum(X, axis=0) # 每一列的和，沿着行方向进行运算

array([24, 28, 32, 36])

In [14]:
np.sum(X, axis=1) # 每一行的和，沿着列方向进行计算，可以理解为，传入的axis是多少，是要把这个轴给压缩掉ss

array([ 6, 22, 38, 54])

In [15]:
np.prod(X) # 矩阵所有元素的乘积

0

In [16]:
np.prod(X + 1)

20922789888000

In [17]:
np.mean(X) # 求平均值

7.5

In [18]:
np.median(X) # 求中位数

7.5

In [19]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [20]:
np.median(v) 

2.0

In [22]:
np.percentile(big_array, q=50) # 有50%的元素都小于np.percentile(big_array, q=50)的返回

0.5001574311590118

In [23]:
np.median(big_array)

0.5001574311590118

In [24]:
np.percentile(big_array, q=100) # 最大值

0.9999999608614992

In [25]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

1.592697569385848e-07
0.2502549279172791
0.5001574311590118
0.7504881862406897
0.9999999608614992


In [26]:
np.var(big_array) # 方差

0.08334242463834689

In [27]:
np.std(big_array) # 标准差

0.2886908807675554

In [28]:
X = np.random.normal(0, 1, size=1000000) # 生成满足均值为0，标准差为1，大小为1000000的满足正态分布的数组

In [29]:
np.mean(X) 

0.00017767883884926125

In [30]:
np.std(X)

0.9988017219139194

# 索引

In [31]:
np.min(X)

-4.839424531363924

In [32]:
np.argmin(X) # X的最小值的索引

136599

In [33]:
X[136599]

-4.839424531363924

In [34]:
np.argmax(X) # X的最大值的索引

985393

In [35]:
X[985393]

4.52674761335934

In [36]:
np.max(X)

4.52674761335934

## 排序和使用索引

In [47]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [48]:
np.random.shuffle(x) # 对向量进行乱序
x

array([ 1,  0, 13,  4,  3,  5, 11,  8,  7, 15, 12,  6, 10,  2,  9, 14])

In [49]:
np.sort(x) # 排序

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [50]:
x  # 并没有改变X本身顺序

array([ 1,  0, 13,  4,  3,  5, 11,  8,  7, 15, 12,  6, 10,  2,  9, 14])

In [51]:
x.sort()  # 改变X本身顺序

In [52]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [43]:
X = np.random.randint(10, size=(4,4))
X

array([[0, 2, 2, 8],
       [4, 6, 8, 1],
       [8, 8, 9, 4],
       [4, 8, 1, 6]])

In [44]:
np.sort(X) # 把每一行按照顺序排序

array([[0, 2, 2, 8],
       [1, 4, 6, 8],
       [4, 8, 8, 9],
       [1, 4, 6, 8]])

In [45]:
np.sort(X, axis=1) # 默认值为1, 沿着列方向进行排序，就将每一行排好了序

array([[0, 2, 2, 8],
       [1, 4, 6, 8],
       [4, 8, 8, 9],
       [1, 4, 6, 8]])

In [46]:
np.sort(X, axis=0) # 沿着行的方向进行排序，将每一列排好了序

array([[0, 2, 1, 1],
       [4, 6, 2, 4],
       [4, 8, 8, 6],
       [8, 8, 9, 8]])

In [53]:
np.random.shuffle(x)
x

array([ 1,  5,  2,  7,  4, 14, 13,  6,  9,  3,  0, 10, 15,  8, 12, 11])

In [54]:
np.argsort(x) # 存放的是元素的索引

array([10,  0,  2,  9,  4,  1,  7,  3, 13,  8, 11, 15, 14,  6,  5, 12])

In [55]:
np.partition(x, 3) # 3前面的比3小，3后面的比3大

array([ 0,  2,  1,  3,  4,  5,  6, 13,  9, 14,  7, 10, 15,  8, 12, 11])

In [57]:
np.argpartition(x, 3) # 返回元素的索引值

array([10,  2,  0,  9,  4,  1,  7,  6,  8,  5,  3, 11, 12, 13, 14, 15])

In [58]:
X

array([[0, 2, 2, 8],
       [4, 6, 8, 1],
       [8, 8, 9, 4],
       [4, 8, 1, 6]])

In [60]:
np.argsort(X, axis=1) # 返回的是相应的索引

array([[0, 1, 2, 3],
       [3, 0, 1, 2],
       [3, 0, 1, 2],
       [2, 0, 3, 1]])

In [61]:
np.argsort(X, axis=0) 

array([[0, 0, 3, 1],
       [1, 1, 0, 2],
       [3, 2, 1, 3],
       [2, 3, 2, 0]])

In [62]:
np.argpartition(X, 2, axis=1) # 索引表

array([[0, 1, 2, 3],
       [3, 0, 1, 2],
       [3, 1, 0, 2],
       [2, 0, 3, 1]])