# 07-numpy.array中的运算

给定一个向量，让向量中每一个数乘以2 <br>
a = (0, 1, 2) <br>
a * 2 = (0, 2, 4)

In [3]:
n = 10
L = [i for i in range(n)]

In [4]:
2 * L # Python原生

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
A = []
for e in L:
    A.append(2 * e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [9]:
n = 1000000
L = [i for i in range(n)]

In [10]:
%%time
A = []
for e in L:
    A.append(2 * e)

CPU times: user 126 ms, sys: 20.5 ms, total: 147 ms
Wall time: 146 ms


In [11]:
%%time
A = [2 * e for e in L]

CPU times: user 53 ms, sys: 15.1 ms, total: 68.1 ms
Wall time: 67.2 ms


In [12]:
import numpy as np
L = np.arange(n) # 使用numpy

In [16]:
%%time
A = np.array(2 * e for e in L) # 1

CPU times: user 20 µs, sys: 0 ns, total: 20 µs
Wall time: 22.9 µs


In [17]:
%%time
A = 2 * L # 2

CPU times: user 3.12 ms, sys: 3.69 ms, total: 6.81 ms
Wall time: 4.87 ms


In [15]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [18]:
n = 10
L = np.arange(n)
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Funtions

In [20]:
X = np.arange(1, 16).reshape((3, 5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [21]:
X + 1 # 所有元素都+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [22]:
X - 1 # 所有元素都-1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
X * 2 # 所有元素都*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [24]:
X / 2 # 所有元素都 /2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [25]:
X // 2 # 整数触法

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [26]:
X ** 2 # 所有元素都平方

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [27]:
X % 2 

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [28]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [29]:
np.abs(X) # 求绝对值

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [30]:
np.sin(X) # 求sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [31]:
np.cos(X) # 求cos

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [32]:
np.tan(X) # 求tan

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [33]:
np.exp(X) # 求exp

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [34]:
np.power(3, X) # 求3的次方

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [35]:
3 ** X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [37]:
np.log(X) # 取log值, 以e为底

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [38]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [39]:
np.log10(X) 

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

## 矩阵运算

In [41]:
A = np.arange(4).reshape((2, 2))
A

array([[0, 1],
       [2, 3]])

In [42]:
B = np.full((2, 2), 10)
B

array([[10, 10],
       [10, 10]])

In [43]:
A + B # 矩阵相加

array([[10, 11],
       [12, 13]])

In [44]:
A - B # 矩阵相减

array([[-10,  -9],
       [ -8,  -7]])

In [45]:
A * B # 矩阵对应元素相乘

array([[ 0, 10],
       [20, 30]])

In [46]:
A / B # 矩阵对应元素相除

array([[0. , 0.1],
       [0.2, 0.3]])

In [47]:
A.dot(B) # A 与 B矩阵相乘

array([[10, 10],
       [50, 50]])

In [48]:
A

array([[0, 1],
       [2, 3]])

In [49]:
A.T # 矩阵转制

array([[0, 2],
       [1, 3]])

In [50]:
C = np.full((3, 3), 666)

In [51]:
A + C # 非法

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [52]:
A.dot(C) # 非法

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

## 向量和矩阵的运算

In [53]:
v = np.array([1, 2])

In [54]:
A

array([[0, 1],
       [2, 3]])

In [55]:
v + A # 向量v和矩阵中的每一行做加法

array([[1, 3],
       [3, 5]])

In [56]:
np.vstack([v] * A.shape[0]) # 将v垂直填充到和A相同行

array([[1, 2],
       [1, 2]])

In [57]:
np.vstack([v] * A.shape[0]) + A # 将v垂直填充到和A相同行后进行相加

array([[1, 3],
       [3, 5]])

In [58]:
np.tile(v, (2, 1)) # 行向量堆叠2次，列向量堆叠1次

array([[1, 2],
       [1, 2]])

In [60]:
np.tile(v, (2, 1)) + A # 堆叠后相加

array([[1, 3],
       [3, 5]])

In [61]:
v

array([1, 2])

In [62]:
A

array([[0, 1],
       [2, 3]])

In [64]:
v * A # v和A中每个向量做乘法，且按照numpy的语法，是向量对应元素做乘法

array([[0, 2],
       [2, 6]])

In [66]:
v.dot(A) # 矩阵乘法

array([4, 7])

In [67]:
A.dot(v) # 依然可以，行向量和列向量可以互换

array([2, 8])

## 矩阵的逆

In [68]:
A

array([[0, 1],
       [2, 3]])

In [70]:
np.linalg.inv(A) # 计算A的逆矩阵

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [71]:
invA = np.linalg.inv(A) # 求A的逆矩阵

In [72]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [73]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [75]:
X = np.arange(16).reshape((2, 8))
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [76]:
np.linalg.inv(X) # 非法

LinAlgError: Last 2 dimensions of the array must be square

In [77]:
pinvX = np.linalg.pinv(X) # 求伪逆矩阵

In [78]:
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [79]:
pinvX.shape

(8, 2)

In [80]:
X.shape

(2, 8)

In [81]:
X.dot(pinvX) # 原矩阵和伪逆矩阵的乘积为单位矩阵

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])