# KNN in Scikit-Learn

In [17]:
import numpy as np
import matplotlib.pyplot as plt

raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([[8.093607318, 3.365731514]])

In [9]:
%run KNN_function/KNN.py # 使用函数的方式将算法封装

In [7]:
predict_y = KNN_classify(6, X_train, y_train, x)

In [8]:
predict_y

1

**可以说KNN是机器学习中不需要训练过程的算法**

KNN算法是非常特殊的，可以认为是没有模型的算法<br>
为了和其他算法统一，可以认为训练数据集就是模型本身

## 使用scikit-learn中的KNN

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6) # 创建一个KNN_classifier对象

In [20]:
kNN_classifier.fit(X_train, y_train) # 先进行拟合

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [19]:
kNN_classifier.predict(x) # 需要传入二维数组

array([1])

In [21]:
X_predict = x.reshape(1, -1)

In [22]:
X_predict

array([[8.09360732, 3.36573151]])

In [23]:
kNN_classifier.predict(X_predict)

array([1])

In [24]:
y_predict = kNN_classifier.predict(X_predict)

In [25]:
y_predict[0]

1

## 重新整理我们的KNN的代码

In [30]:
%run KNN/KNN.py

In [31]:
knn_clf = KNNClassifier(k=6)

In [32]:
knn_clf.fit(X_train, y_train)

KNN(k=6)

In [33]:
y_predict = knn_clf.predict(X_predict)

In [34]:
y_predict

array([1])

In [35]:
y_predict[0]

1