# 05-06-numpy.array的基本操作

In [1]:
import numpy as np

In [7]:
x = np.arange(10)

In [8]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
X = np.arange(0, 15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 1. 基本属性

In [9]:
x.ndim # 查看是几维数组

1

In [10]:
X.ndim

2

In [11]:
x.shape # (10, )表示是一个一维数组

(10,)

In [12]:
X.shape # (3, 5)表示3行5列

(3, 5)

In [13]:
x.size # 元素个数

10

In [14]:
X.size # 元素个数

15

## 2. numpy.array的数据访问

In [15]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x[0] # 通过索引访问

0

In [19]:
x[-1] # 表示最后一个

9

In [20]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
X[0][0] # 通过索引访问

0

In [23]:
X[(2,2)] # 通过索引访问

12

In [24]:
X[2, 2] # 通过索引访问(推荐)

12

In [26]:
x[0:5] # 切片，左闭右开

array([0, 1, 2, 3, 4])

In [27]:
x[:5] # 从头开始

array([0, 1, 2, 3, 4])

In [28]:
x[5:] # 访问到结尾

array([5, 6, 7, 8, 9])

In [29]:
x[::2] # 第三个参数为步长,从头到尾

array([0, 2, 4, 6, 8])

In [30]:
x[::-1] # 倒序访问

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [31]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
X[:2, :3] # 前2行，前3列

array([[0, 1, 2],
       [5, 6, 7]])

In [33]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
X[:2][:3] # 解析为X[:2]的前3行

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
X[:2, ::2] # 前2行，每行访问从头到尾，step=2

array([[0, 2, 4],
       [5, 7, 9]])

In [37]:
X[::-1, ::-1] # 行从尾到头，列从尾到头

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [38]:
X[0] # 第1行

array([0, 1, 2, 3, 4])

In [40]:
X[0, :]

array([0, 1, 2, 3, 4])

In [41]:
X[0, :].ndim

1

In [42]:
X[:, 0] # 第1列

array([ 0,  5, 10])

In [44]:
X[:, 0] # 第1列

array([ 0,  5, 10])

In [45]:
X[:, 0].ndim

1

In [47]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [49]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [50]:
X # numpy中修改子矩阵后原矩阵也被改变

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [52]:
X[0,0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
subX # numpy中修改原矩阵后子矩阵也被改变

array([[0, 1, 2],
       [5, 6, 7]])

In [55]:
subX = X[:2, :3].copy() # 创建一个和原矩阵不相关的矩阵
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [56]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [57]:
X # 原矩阵不再发生变化

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 3. reshape

In [58]:
x.shape # 一维向量，有10个元素

(10,)

In [59]:
x.ndim

1

In [60]:
x.reshape(2, 5) # 变成2 * 5的矩阵

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
x # x未发生改变

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
B = x.reshape(1, 10) # 修改为1 * 10的二维矩阵

In [65]:
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [66]:
B.ndim

2

In [67]:
B.shape

(1, 10)

In [68]:
x.reshape(10, -1) # 希望x有10行，而不关心列

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [69]:
x.reshape(-1, 10) # 不关心多少行，但需要有10列

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [70]:
x.reshape(2, -1) 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
x.reshape(3, -1) # 10不能被3整除

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

## 4. 合并操作

In [72]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [73]:
x

array([1, 2, 3])

In [74]:
y

array([3, 2, 1])

In [76]:
np.concatenate([x, y]) # 合并为1 * 6的向量

array([1, 2, 3, 3, 2, 1])

In [77]:
z = np.array([666, 666, 666])

In [78]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [79]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [80]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [81]:
np.concatenate([A, A], axis=1) # 沿着第二个维度拼接, 列的方向

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [82]:
z

array([666, 666, 666])

In [84]:
np.concatenate([A, z]) # 维数不同不能直接拼接

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [85]:
np.concatenate([A, z.reshape(1, -1)]) # 将z转为二维

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [86]:
A # 连接的结果是一个新的矩阵

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
A2 = np.concatenate([A, z.reshape(1, -1)]) # 需要赋值给新的矩阵
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [90]:
np.vstack([A, z]) # 使用vstack可以将不同维度的数组垂直拼接

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [92]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [93]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
np.concatenate([A, B], axis=1)

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [95]:
np.hstack([A, B]) # 将A和B在水平方向堆叠在一起

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [96]:
np.hstack([A, z]) # 非法

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

## 5. 分割操作

In [98]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
x1, x2, x3 = np.split(x, [3, 7]) # 从3，7分割为3段

In [104]:
x1

array([0, 1, 2])

In [105]:
x2

array([3, 4, 5, 6])

In [106]:
x3

array([7, 8, 9])

In [107]:
x1, x2 = np.split(x, [5]) # 从5开始分割为2段

In [108]:
x1

array([0, 1, 2, 3, 4])

In [109]:
x2

array([5, 6, 7, 8, 9])

In [111]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [112]:
A1, A2 = np.split(A, [2]) # 在行方向上，从2分割成2部分

In [113]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [114]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [116]:
A1, A2 = np.split(A, [2], axis=1) # 在列方向上，从2开始分割成2部分

In [117]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [118]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [119]:
upper, lower = np.vsplit(A, [2]) # 从2开始进行垂直分割

In [120]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [121]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [122]:
left, right = np.hsplit(A, [2]) # 从2开始进行水平分割

In [123]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [124]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [125]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [126]:
x, y = np.hsplit(data, [-1]) # 将最后一列分割出来

In [127]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [128]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [130]:
y[:, 0] # 将第一列抽出来，成为向量

array([ 3,  7, 11, 15])